name: test

on:
  pull_request:
    branches: main
  workflow_dispatch:


jobs:
  compile-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install
      - run: rm -rf dist
      - run: tsc
      - run: npm test